spring.application.name=tflkafka
# logging.level.root=WARN
# logging.level.com.vnadkarni=INFO

# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer