spring.application.name=tflkafka
logging.level.root=WARN
logging.level.com.vnadkarni=WARN

logging.level.org.apache.kafka=WARN
logging.level.org.springframework=WARN
logging.level.io.confluent=WARN

# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=<bootstrap server ending in port :9092>
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='<API KEY>' password='<API SECRET>';
sasl.mechanism=PLAIN
# Required for correctness in Apache Kafka clients prior to 2.6
client.dns.lookup=use_all_dns_ips

# Best practice for higher availability in Apache Kafka clients prior to 3.0
session.timeout.ms=45000

# Best practice for Kafka producer to prevent data loss
acks=1

client.id=<client id>


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

schema.registry.url=<Schema Registry server>
schema.registry.basic.auth.credentials.source=USER_INFO
schema.registry.basic.auth.user.info=YOUR_SCHEMA_REGISTRY_API_KEY:YOUR_SCHEMA_REGISTRY_API_SECRET
# SR API KEY & SECRET are different from key & secret for Kafka, even for the same Service Account.